### ISSUE TITLE
BM25 Keyword Search Returns No Results Despite Documents Existing in Collection

### ISSUE THREAD

**Issue by haseebrj17** [topk-io/topk#182]
### Description
BM25 keyword search using `match()` function returns empty results even though documents exist in the collection. Additionally, using the `contains()` operator results in internal server errors.

### Environment
- TopK SDK version: 0.4.6
- Python version: 3.12
- Region: aws-us-east-1-elastica

### Steps to Reproduce

1. Created a collection with keyword-indexed fields:
```python
"content": text().required().index(keyword_index()),
```

2. Successfully inserted 158 documents into the collection (confirmed with count query)

3. Attempted BM25 search:
```python
bm25_results = collection.query(
    select(
        "content",
        text_score=fn.bm25_score(),
    )
    .filter(
        match("risks") | match("mitigation") | match("strategies")
    )
    .topk(field("text_score"), 50, asc=False)
)
# Returns: []
```

4. Even searching for common words returns no results:
```python
bm25_results = collection.query(
    select("content", text_score=fn.bm25_score())
    .filter(match("the"))
    .topk(field("text_score"), 5, asc=False)
)
# Returns: []
```

5. Attempting to use `contains()` operator as workaround results in error:
```python
results = collection.query(
    select("content", "document_id")
    .filter(
        field("content").contains("risk") |
        field("content").contains("mitigation") |
        field("content").contains("strategy")
    )
    .topk(literal(1), 50)
)
# Exception: topk returned error: Unexpected("unexpected error: Status { code: Internal, message: 
# "An internal error occurred. If the problem persists, please contact us at support@topk.io"...
```

### Expected Behavior
- BM25 search should return documents containing the specified keywords
- `match()` function should work with keyword-indexed fields
- `contains()` operator should not cause internal errors

### Actual Behavior
- All BM25 searches return empty results regardless of search terms
- Even common words like "the", "and", "or" return no results
- `contains()` operator causes internal server error

### Additional Context
- Vector search (using `vector_distance()`) works correctly on the same collection
- Document count confirms 158 documents exist
- Schema includes `keyword_index()` on the content field

### Possible Issues
1. Keyword index may not be built/initialized properly when documents are inserted
2. Text tokenization/processing might not be working as expected
3. There may be a configuration issue with keyword indexes

### Workaround Needed
Currently unable to perform any text-based search on documents. Need either:
- Fix for BM25/keyword search functionality
- Alternative method for text search without relying on keyword indexes

**Comment by marekgalovic** [comment]
Hey @haseebrj17! Do any of the documents contain one of these keywords `{risks, mitigation, strategies}`? Our text pipeline currently doesn't perform stemming, so unless these _exact_ keywords are present (case insensitive), the expected result should be empty.

We fixed the issue with literal top_k input (`topk(literal(1), 50)`). Will deploy soon.

**Comment by haseebrj17** [comment]
@marekgalovic Yes, the document contains the exact strings at multiple places, yet I am still getting an empty [] list back.
